# Use a newer version of the SDK to fix the virtual package detection for macOS
# Otherwise `SYSTEM_VERSION_COMPAT` needs to be set to `0` to detect the proper macOS version
c_stdlib_version:              # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
rust_compiler_version:         # [osx and x86_64]
  - 1.85.1                     # [osx and x86_64]
