{% set name = "rattler-build" %}
{% set version = "0.6.2rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/rattler-build/archive/2ba8703e161bf86701c5fa91e1da61e7592bdede.tar.gz
  sha256: 51aa10d90d413fd9746b4f8c495432bf03283660de2e4596f838982f34d3a5b0

build:
  script:
    # Unix recipe
    - export OPENSSL_DIR="$PREFIX"                                            # [unix]
    - cargo install --locked --bins --root ${PREFIX} --path .                 # [unix]
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # [unix]
    - rm $PREFIX/.crates2.json                                                # [unix]
    - rm $PREFIX/.crates.toml                                                 # [unix]
    # Win recipe
    - cargo install --locked --bins --root %PREFIX% --path .                  # [win]
    - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml   # [win]
    - del %PREFIX%\.crates2.json                                              # [win]
    - del %PREFIX%\.crates.toml                                               # [win]
  number: 0
  # disable binary prefix detection, because rattler-build encodes the old `anaconda1anaconda2anaconda3` prefix
  # somewhere to make old packages installable. In other words, conda-build finds a false-positive here.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # to compile the libsolv parts
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - openssl  # [linux]

test:
  commands:
    - rattler-build --help

about:
  home: https://github.com/prefix-dev/rattler-build
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
  description: |
    The rattler-build tooling and library creates cross-platform relocatable binaries / packages 
    from a simple recipe format.
    The recipe format is heavily inspired by conda-build and boa, and the output of a regular
    rattler-build run is a package that can be installed using mamba, conda or rattler.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - CONDA_BUILD_LICENSE.txt
  doc_url: https://prefix-dev.github.io/rattler-build

extra:
  recipe-maintainers:
    - wolfv
    - pavelzw
